name: uda-2019-inversion

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - jupyterlab>=1.1.0
  - mkl
  - deepdish
  - SimPEG
  - pymatsolver
  - pip:
    - jupyterlab_hdf
