name: uda-2019-inversion

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - ipywidgets
  - jupyterlab>=1.1.0,<2.0
  - mkl
  - deepdish
  - SimPEG==0.13.1
  - pymatsolver==0.1.2
  - h5py
